pln-planning-tools/Starmap

- components/roadmap-grid/Roadmap.module.css
- components/roadmap-grid/RoadmapSimpleView.tsx
Fixes https://github.com/pln-planning-tools/MapLight/issues/52
> Properly render level one milestones for simple view

- components/roadmap-grid/Roadmap.tsx
- components/roadmap-grid/RoadmapDetailedView.tsx
- components/roadmap-grid/grid-header.tsx
- components/roadmap-grid/grid-row.tsx
- lib/parser.ts
- pages/roadmap/[...slug].tsx
- utils/regexes.ts
> fix: show error message for issue not found & filter children by title `children`

- components/layout/PageHeader.module.css
- components/layout/PageHeader.tsx
- package.json
- pages/LandingPage.module.css
- pages/index.tsx
- yarn.lock
> feat: render User Guide.md on landing page

- components/roadmap-grid/Roadmap.module.css
- components/roadmap-grid/grid-row.tsx
Closes: #61 
Demo: https://starmaps-git-61-entire-milestone-box-should-6cf278-ipfs-ignite.vercel.app/roadmap/github.com/ipfs/roadmap/issues/102?view=detail
> chore: make entire milestone item clickable

- lib/client/getDateAsQuarter.ts
- lib/helpers.ts
Closes #108 
This was caused by the missing `i` - case ignore flag at the end.
> fix: Ignore Case for ETA regex

- components/roadmap-grid/grid-row.tsx
- pages/api/roadmap.ts
Closes: #110 
In this PR:
- if issue is closed, the completion is 100%
- Changing color to green.
> fix: Progress Milestone for children with no grand children

- User Guide.md
Updated user guide to include "getting started" steps and for clarity. 
Added:
- "How to Use" section
- how-to guide for using starmaps.app that will exist on the site itself.
- Label section (based on new requirements)
- instruction to include starmaps label on each issue
- Issue title (based on testing observation)
- guidance that the issue title will render in starmaps
- Example added (Based on user feedback)
- link to kubo test issue
- clarified that existing issues can be used as child milestones
Modified:
- Small edits everywhere for clarity
- Capabilities (based on new requirements)
- Fundamentals (based on new requirements)
- Child milestones (based on how the tool functions)
- tried to update the wording around "milestone" and "root node" to make more clear as to what each is …
> Update User Guide.md

- components/roadmap-grid/grid-row.tsx
fixes https://github.com/pln-planning-tools/Starmaps/issues/125
> fix: use exact dates in milestone cards

- components/roadmap-grid/grid-row.tsx
- lib/client/getTicks.ts
- lib/helpers.ts
- lib/parser.ts
- lib/types.d.ts
- pages/api/roadmap.ts
- fix: eta not required on root issue
- fix: remove duplicate date tick labels
- fix: don't render milestone items if date is invalid
> fix: multiple fixes

- components/roadmap-grid/RoadmapTabbedView.tsx
- hooks/useViewMode.ts
note: localStorage caching of value is no longer working
> fix: tab view switching

- components/roadmap-grid/RoadmapTabbedView.tsx
- lib/backend/errorManager.ts
- lib/paramsFromUrl.ts
- pages/api/roadmap.ts
- pages/roadmap/[...slug].tsx
- tests/unit/paramsFromUrl.test.ts
- chore: get paramsFromUrl tests passing
- feat: deep-link viewMode with hashRouting
fixes #142 
fixes #158
> feat: deep-link viewMode with hashRouting

- .vscode/settings.json
- components/roadmap-grid/RoadmapDetailedView.tsx
- components/roadmap-grid/RoadmapTabbedView.tsx
- components/roadmap-grid/grid-row.tsx
- components/roadmap-grid/header.tsx
- components/roadmap-grid/headerline.tsx
- lib/addChildToParentIssue.ts
- lib/client/convertIssueDataToDetailedViewGroup.ts
- lib/types.d.ts
> Enhancements

- jest.config.js
- package.json
- tsconfig.json
Closes: #183 
This reports correct code coverage.
> fix: Coverage reporting for all files

- components/roadmap-grid/Roadmap.module.css
> fix: updated today marker styling for issue 206

- components/errors/ErrorLineItemDescription.tsx
- components/errors/ErrorNotificationBody.module.css
- components/errors/ErrorNotificationBody.tsx
> feat: fix padding in error log

- pages/LandingPage.module.css
> fix: 252 user guide styles

- User Guide.md
fixes: #286 
- update to the user guide templates that were causing some confusion and did not match the current logic
> fix: 286 update to user guide to reflect current logic 

- User Guide.md
- lib/backend/getGithubIssueDataWithGroupAndChildren.ts
- lib/backend/issue.ts
- lib/parser.ts
- lib/types.d.ts
- pages/api/roadmap.ts
- tests/unit/parser.test.ts
- feat: support children via GitHub Taskslist (#315)
- Revert "feat: support children via GitHub Taskslist (#315)" to fix #324 (#326)
- Revert "Revert "feat: support children via GitHub Taskslist (#315)" to fix #324 (#326)"
closes #324
> feat: support tasklists

- package.json
- pages/_app.tsx
- pages/api/pendingChild.ts
- pages/api/roadmap.ts
- pages/roadmap/[...slug].tsx
- sw/CacheChildrenStrategy.ts
- sw/service-worker.ts
- yarn.lock
- feat: use vercel edge-network caching
fixes #335
> feat: use vercel edge-network cache

- sw/CacheChildrenStrategy.ts
This prevents issues like those found at https://github.com/pln-planning-tools/Starmap/issues/345
fixes https://github.com/pln-planning-tools/Starmap/issues/345
> feat: add cache version to cacheKey
