- User Guide.md
- Swapped all instances of "Maplight" to "StarMaps"
- In order to satisfy requirement for all issues to have "roadmap" label in order to render in StarMaps, replaced:
> Milestones are simply Github Issues with the "milestone" label. StarMaps will only render issues with this label
with
> Both Roadmap and Milestone issues require the "roadmap" label. StarMaps will only render issues with the "roadmap" label
> Update User Guide.md

- components/roadmap-grid/grid-header.tsx
- lib/client/dayjs.ts
- chore: add dayjs quarterofyear plugin
- feat: use Quarter identifier for labels
> feat: use quarters as labels instead of dates

- components/roadmap-grid/grid-row.tsx
Closes: #62 
This is a temp fix till we have a better UX around milestones with no children.
> fix(click): Preventing navigation on items with no-children

- components/roadmap-grid/grid-header.tsx
- components/roadmap/RoadmapHeader.tsx
- config/constants.ts
- lib/client/getTicks.ts
- lib/helpers.ts
Closes: #92 
@SgtPooki I am not even sure if this is what you had in mind, but in this PR:
- I am calculating the diff between `max` and `min`
- Adding and subtracting quarter till the required threshold is reached.
- Skewed milestones get roughly aligned in the centre.
Feel free to close this if this is not something that would work.
> fix (quarter-labels): Should not be duplicated

- components/roadmap-grid/RoadmapDetailedView.tsx
- components/roadmap-grid/grid-row.tsx
Closes: #100 
In this PR:
- Recalculating ticks with headers as the source of truth, the intuition behind that is this alignment of header with the grid:
Demo: https://starmaps-git-fix-tick-alignment-ipfs-ignite.vercel.app/roadmap/github.com/filecoin-project/bacalhau/issues/1151
> fix: Fixing Tick Alignment Calculations

- components/RoadmapForm.tsx
- components/roadmap-grid/RoadmapDetailedView.tsx
- components/roadmap-grid/grid-row.tsx
- lib/backend/issue.ts
- lib/client/dateUtils.ts
- lib/client/linkUtils.ts
- lib/general.ts
- lib/getValidUrlFromInput.ts
- lib/paramsFromUrl.ts
- lib/slugsFromUrl.ts
- lib/types.d.ts
- pages/api/roadmap.ts
- tests/unit/getValidUrlFromInput.test.ts
- tests/unit/paramsFromUrl.test.ts
- tests/unit/slugsFromUrl.test.ts
- chore: move utils/general.ts -> lib/general.ts
- feat: support more github-esque url strings
* `https://github.com/pln-planning-tools/Starmaps/issues/1`
* `github.com/pln-planning-tools/Starmaps/issues/1`
* `github.com/pln-planning-tools/Starmaps#1`
* `pln-planning-tools/Starmaps/issues/1`
* `pln-planning-tools/Starmaps#1`
- feat: much better url error handling
> feat: significantly polish github url entry

- lib/client/getTicks.ts
- pages/api/roadmap.ts
This fix may not completely resolve #121, but it does solve one use case and renders the error collection notification providing valuable information.
> feat: handle the 'not found' error more gracefully

- User Guide.md
According to the parser implementation
https://github.com/pln-planning-tools/StarMaps/blob/0d41d94ca118efde9ea15948ecfb61e97e9db84a/lib/helpers.ts#L12 the date must be either in ISO 8601 format or specified with a quarter. This commit updates the user guide accordingly.
> docs: eta date must be in ISO format/with quarter

- components/roadmap-grid/RoadmapTabbedView.tsx
- hooks/useViewMode.ts
- lib/defaults.ts
Closes: #99 
This fixes the weird `localStorage` behaviour 🤞🏽 
RCA:
- The value seems to change and then quickly revert back to the previous. This likely happens because the both functions are not setting the same value.
- IRL we don't need to `setState` the second time.
> fix: removing additional set state

- components/inputs/NumSlider.tsx
- components/roadmap-grid/Roadmap.module.css
- components/roadmap-grid/RoadmapDetailedView.tsx
- components/roadmap-grid/grid-header.tsx
- components/roadmap-grid/grid-row.tsx
- components/roadmap-grid/grid.tsx
- components/roadmap-grid/headerline.tsx
- components/roadmap-grid/today-marker.module.css
- components/roadmap-grid/today-marker.tsx
- hooks/useGlobalTimeScale.ts
- lib/client/TimeScaler.ts
- lib/client/getTicks.ts
- pages/roadmap/[...slug].tsx
- feat: create global scaleTime hook
- feat: add NumSelector slider component
- tmp
- feat: make header grid-column-end dynamic
- feat: ensure milestone item width is adjustable
- feat: display current value in NumSlider
- chore: remove unused code
- feat: make gridCol changes smoother
- chore: fix accuracy of milestone items
Fixes #135. 
fixes #34 
A few changes to the way roadmaps are rendered:
1. Header and positioning does not jump when toggling between Overview and Detailed view 
2. Roadmaps are no longer centered on Todays date. Roadmaps are centered to a view that contains all provided dates.
* Today line is visible now to compensate for this. @juliaxbow I can remove this if it's not ideal and we can iterate later
* "Today" text can be clicked to hide the line if desired.
3. …
> feat: fix css-grid milestone accuracy

- pages/roadmap/[...slug].tsx
- fix: catch-any error on roadmap page
Adding a catch-all for errors instead of getting a 500 error. proven with a forced SSL error when attempting to run locally:
partial fix for #158
> fix: roadmap 500 errors display on page

- hooks/useAsync.ts
- lib/backend/addToChildren.ts
- lib/backend/calculateCompletionRate.ts
- lib/backend/convertParsedChildToGroupedIssueData.ts
- lib/backend/getGithubIssueDataWithGroupAndChildren.ts
- lib/backend/resolveChildren.ts
- lib/backend/resolveChildrenWithDepth.ts
- lib/types.d.ts
- pages/api/pendingChild.ts
- pages/api/roadmap.ts
- pages/roadmap/[...slug].tsx
- tests/unit/backend/calculateCompletionRate.test.ts
- fix: better error handling for children
- feat: start working on async loading of children
- chore: clean-up code for breaking up roadmap.ts
replaces https://github.com/pln-planning-tools/StarMaps/pull/169
precursor to https://github.com/pln-planning-tools/StarMaps/pull/170
> chore: break-up roadmap.ts

- components/icons/svgr/SvgGitHubLogoWithTooltip.tsx
- components/roadmap-grid/Roadmap.module.css
- components/roadmap-grid/grid-row.tsx
Closes Issues #150 
-  Updated styling and minor layout changes to grid-row
-  Smaller screens will change to a stacked view within the card (as discussed with @juliaxbow )
-  Added back ellipsis as screen sizes scale down and text gets cutoff
> fix: styling and layout for github icons

- .env.development
- components/RoadmapForm.tsx
- components/roadmap-grid/RoadmapDetailedView.tsx
- components/roadmap/NewRoadmap.tsx
- config/constants.ts
- hooks/useGlobalLoadingState.ts
- hooks/useIsLoading.ts
- lib/backend/errorManager.ts
- lib/backend/getGithubIssueDataWithGroupAndChildren.ts
- lib/groupStarMapsErrors.ts
- lib/types.d.ts
- package.json
- pages/roadmap/[...slug].tsx
- yarn.lock
1. Ensures initial page request of /roadmap/github.com/ipfs/roadmap/issues/102#detail returns without needing to wait on querying all the issues
2. Loads the issues (via /api/roadmap) from the RoadMap page, client side.
3. gets us closer to fully loading nested children from the client (see branch `fix/bacalhau-1151-with-async-children`)
4. significantly improves first load time and isolates backend request time which limits risks that vercel limits will bite us.
-   feat: update global isLoading
-   fix: react key error
-   chore: update errorManager
-   chore: update getGithubIssueDataWithGroupAndChildren
-   feat: load roadmap after initial server response
-   fix: types
This issue continues along with a number of other issues to resolve #158:
-   builds further on #179
-   fixes #180 …
> feat: make api/roadmap call from client

- components/errors/ErrorNotificationDisplay.tsx
- components/errors/ErrorNotificationHeader.tsx
- components/roadmap-grid/grid.tsx
- components/roadmap-grid/today-marker.module.css
- pages/roadmap/[...slug].tsx
Addresses: https://github.com/pln-planning-tools/StarMaps/pull/207#issuecomment-1331568815
In this PR:
- Making the entire container scroll to reveal roadmap.
- Fixing roadmap after height is reached.
- Bonus: Added issue count.
> fix: Scrolling with errors

- components/roadmap-grid/RoadmapDetailedView.tsx
- hooks/usePrevious.ts
- lib/client/getUniqIdForGroupedIssues.ts
- tests/unit/client/getUniqIdForGroupedIssues.test.ts
- fix: milestones are accurate when strictMode=false
- feat: use uniq id for grouped issues
- https://github.com/drand/roadmap/issues/1 - [demo link](https://starmaps-git-236-bug-milestone-alignment-is-off-ipfs-ignite.vercel.app/roadmap/github.com/drand/roadmap/issues/1)
- https://github.com/cryptonetlab/roadmap/issues/22 - [demo link](https://starmaps-git-236-bug-milestone-alignment-is-off-ipfs-ignite.vercel.app/roadmap/github.com/cryptonetlab/roadmap/issues/22)
> fix: address milestone alignment re-rendering

- User Guide.md
- lib/backend/getGithubIssueDataWithGroupAndChildren.ts
- lib/backend/issue.ts
- lib/parser.ts
- lib/types.d.ts
- pages/api/roadmap.ts
- tests/unit/parser.test.ts
Example issue using tasklists: https://github.com/ipfs/ipfs-gui/issues/106
Note that it's milestone children are *not* using tasklists, and their children are still recognized properly. 
demo: https://starmaps-git-313-add-support-for-parsing-tas-282722-ipfs-ignite.vercel.app/roadmap/github.com/ipfs/ipfs-gui/issues/106#simple
> feat: support children via GitHub Taskslist

- .github/workflows/ci.yml
Since coverage reporter needs secrets, forks cannot access that.
> fix(ci): :wrench: Fixing CI to not run coverage reporter when running from fork.

- .github/workflows/ci.yml
had a bad `equal` comparison. It's been broken.
> fix(ci): 🐛 broken CI

- components/icons/svgr/SvgListViewIcon.tsx
- components/roadmap-grid/RoadmapDetailedView.tsx
- components/roadmap-grid/RoadmapTabbedView.tsx
- components/roadmap-grid/grid-row.tsx
- fix: react warnings
- fix: Ensure issuesGroupedState is up to date
fixes https://github.com/pln-planning-tools/Starmap/issues/347
demo url: https://starmaps-git-347-bug-detail-view-not-loading-c9426c-ipfs-ignite.vercel.app/roadmap/github.com/protocol/engres/issues/9#detail
> fix: Ensure issuesGroupedState is up to date

- pages/api/pendingChild.ts
- pages/roadmap/[...slug].tsx
fix #350
You can see the success at https://starmaps-git-350-bug-fetcherrors-from-sw-sho-c305f4-ipfs-ignite.vercel.app/api/pendingChild?owner=drand&repo=roadmap&issue_number=12&parentJson=%7B%22labels%22%3A%5B%5D%2C%22completion_rate%22%3A0%2C%22due_date%22%3A%222023-06-30%22%2C%22html_url%22%3A%22https%3A%2F%2Fgithub.com%2Fprotocol%2Fengres%2Fissues%2F8%22%2C%22group%22%3A%22Children%3A%22%2C%22title%22%3A%22EngRes%20Theme%3A%20Critical%20System%20Stewardship%20%26%20Growth%22%2C%22state%22%3A%22open%22%2C%22node_id%22%3A%22I_kwDOIiXv285gZJEN%22%2C%22parent%22%3A%7B%22state%22%3A%22open%22%2C%22group%22%3A%22root%22%2C%22title%22%3A%22EngRes%20Theme-Based%202023%20Roadmap%22%2C%22html_url%22%3A%22https%3A%2F%2Fgithub.com%2Fprotocol%2Fengres%2Fissues%2F9%22%2C%22labels%22%3A%5B%5D%2C%22nod …
> fix: decode parentJson before parsing it

- components/roadmap/NewRoadmap.tsx
- components/roadmap/lib.ts
- fix: dont loop over each group of binPackedItems
> fix: dont loop over each group of binPackedItems
